name: MinekartaWorldReset
version: 1.0-SNAPSHOT
main: com.minekarta.worldreset.MinekartaWorldReset
api-version: '1.21'
author: Jules
description: Auto World Reset for Papermc
depend: [Multiverse-Core]
softdepend: [PlaceholderAPI]
commands:
  minekartaworldreset:
    description: Main command for MinekartaWorldReset
    usage: /<command> [args]
    aliases: [mwr]
